dentist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('users/', include('users.urls', namespace='users')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
]

tickets/urls.py
from django.urls import path
from .views import TicketListView, TicketCreateView, TicketDetailView, TicketUpdateView, TicketDeleteView


app_name = 'tickets'

urlpatterns = [

    path('', TicketListView.as_view(), name='ticket-list'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),
    path('<int:pk>/update/', TicketUpdateView.as_view(), name='ticket-update'),
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket-delete'),
    path('create/', TicketCreateView.as_view(), name='ticket-create'),
    
]

users/urls.py
from django.urls import path
from .views import DashboardView, UserCreateView, UserLoginView, logout_request, UserCreateView


app_name = 'users'

urlpatterns = [

    path('', DashboardView.as_view(), name='dashboard'),
    path('loggin/', UserLoginView.as_view(), name='login'),
    path('logout/', logout_request, name='logout'),
    path('create-user/', UserCreateView.as_view(), name='create-user')


]

website/urls.py
from django.urls import path
from website.views import LandindPageView

app_name = 'website'

urlpatterns = [

    path('', LandindPageView.as_view(), name='landind_page')

]

tickets/models.py
from django.db import models


class Ticket(models.Model):
    cl_name = models.CharField(max_length=255)
    cl_phone = models.CharField(max_length=255)
    cl_email = models.CharField(max_length=255)
    ticket_subject = models.CharField(max_length=255)
    cl_message = models.CharField(max_length=250)


    def __str__(self):
        return f'''
            {self.cl_name} -
            {self.ticket_subject}
            '''

users/models.py
from django.db import models



class User(models.Model):
    username = models.CharField(max_length=255)
    f_name = models.CharField(max_length=255)
    l_name = models.CharField(max_length=255)
    password = models.CharField(max_length=250, default='Tirane2021.')

    def __str__(self):
        return self.username

website/models.py
from django.db import models

# Create your models here.

tickets/forms.py
from django import forms
from .models import Ticket


class TicketModelForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = (
            'cl_name',
            'cl_phone',
            'cl_email',
        )


class TicketCreateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = (
            'cl_name',
            'cl_phone',
            'cl_email',
            'ticket_subject', 
            'cl_message'
        )

users/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm



class UserCreateForm(UserCreationForm):

    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

tickets/views.py
from django.db.models import query
from django.shortcuts import render, redirect, reverse
from .models import Ticket
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import TicketModelForm,TicketCreateForm
from django.urls import reverse_lazy



class TicketListView(ListView):
    template_name = 'ticket_list.html'
    queryset = Ticket.objects.all()
    context_object_name = 'tickets'




class TicketCreateView(CreateView):
    template_name = 'ticket_create.html'
    form_class = TicketCreateForm
    
    def get_success_url(self):
        print("self.request.GET:", self.request.GET.get("from"))
        coming_from = self.request.GET.get("from")
        url_name = 'tickets:ticket-list'
        if coming_from == "home":
            url_name = "website:landind_page"
        return reverse(url_name)

    def form_valid(self, form):
        print("in form_valid")
        return super().form_valid(form)

    def form_invalid(self, form):
        print("in form_invalid")
        return super().form_invalid(form)


class TicketDetailView(DetailView):
    template_name = 'ticket_detail.html'
    queryset = Ticket.objects.all()
    context_object_name = 'ticket'



class TicketUpdateView(UpdateView):
    template_name = 'ticket_update.html'
    form_class = TicketModelForm
    queryset = Ticket.objects.all()

    
    def get_success_url(self):
        obj = self.get_object()
        return reverse_lazy('tickets:ticket-detail', kwargs={'pk': obj.pk})



class TicketDeleteView(DeleteView):
    template_name = 'ticket_delete.html'
    queryset = Ticket.objects.all()

    def get_success_url(self):
        return reverse('tickets:ticket-list')

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.contrib.auth.views import LoginView   
from django.contrib.auth import logout
from django.contrib.messages import constants as messages
from django.urls import reverse_lazy
from .forms import UserCreateForm


class DashboardView(TemplateView):
    template_name = 'dashboard.html'




class UserLoginView(LoginView):
    template_name = 'login.html'


def logout_request(request):
    logout(request)
    return redirect("users:login")


class UserCreateView(CreateView):
    form_class = UserCreateForm
    template_name = 'create_user.html'
    success_url = reverse_lazy('users:dashboard')
    

website/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView
from tickets.forms import TicketCreateForm

class LandindPageView(TemplateView):
    template_name = 'index.html'

    def get_success_url(self):
        return reverse('landind_page')

tickets/templates/base.html
<nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-address-book"></i>Address Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Components</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Charts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-copy"></i>Documents</a>
                </li>
            </ul>
        </div>
    </nav>




{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    
</head>
<body>
    
    
</body>
</html> {% endcomment %}

tickets/templates/ticket_create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a Ticket</title>
    <link rel="stylesheet" href="{% static 'css/from_label.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="{% static 'css/from_label.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/dashboard_navbar.css' %}">
    <script src="{% static 'js/dashboard_navbar.js' %}"></script>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css'>
    <style>
        .center {
            
            display: flex;
            justify-content: center;
            }
    </style>
</head>
<body>
    

<nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="{% url 'users:dashboard' %}">Navbar</a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-list' %}"><i class="far fa-clone"></i>Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-create' %}"><i class="fas fa-plus"></i>Create a ticket</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Charts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i>Sing Out</a>
                    </li>
                </ul>
            </div>
    </nav>
<br/>
<br/>
<br/>
<div class="center">
    <form method="POST" >
        {% csrf_token %}
        
        {{ form.errors }}
        <div class="group">      
            <input type="text" name='cl_name' required>
            <span class="highlight"></span>
            <span class="bar"></span>
            <label for='id_cl_name'>Full Name</label>
        </div>
        
        <div class="group">      
            <input type="text" name='cl_phone' required>
            <span class="highlight"></span>
            <span class="bar"></span>
            <label for='id_cl_phone'>Phone Number</label>
        </div>
        
        <div class="group">      
            <input type="text" name='cl_email' required>
            <span class="highlight"></span>
            <span class="bar"></span>
            <label for='id_cl_email'>Email Address</label>
        </div>

        <div class="group">      
            <input type="text" name='ticket_subject' required>
            <span class="highlight"></span>
            <span class="bar"></span>
            <label for='id_ticket_subject'>Subject</label>
        </div>

        <div class="group">      
            <input type="text" name='cl_message' required>
            <span class="highlight"></span>
            <span class="bar"></span>
            <label for='id_cl_message'>Message</label>
        </div>
        
        <button type="success" class="btn btn-primary">Create</button>
    
    
    
    </form>
</div>
</body>
</html>

tickets/templates/ticket_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete {{ ticket.cl_name }}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    
</head>
<body>
    
    <a href='{% url "tickets:ticket-list" %}'> Go back to tickets </a>
    <h1>Are you sure you want to delete this ticket?</h1>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Submit</button>
    </form>
    
</body>
</html>

tickets/templates/ticket_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ticket.cl_name }}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dashboard_navbar.css' %}">
    <script src="{% static 'js/dashboard_navbar.js' %}"></script>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css'>
    
</head>
<body>

<nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="{% url 'users:dashboard' %}">Navbar</a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-list' %}"><i class="far fa-clone"></i>Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-create' %}"><i class="fas fa-plus"></i>Create a ticket</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Charts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i>Sing Out</a>
                    </li>
                </ul>
            </div>
    </nav>


      <section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Ticket</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ticket.cl_name}}</h1>
        
            <div class="flex mb-4">
                <a href='{% url "tickets:ticket-detail" ticket.pk %}' class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a  class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Reviews
                </a>
                <a href='{% url "tickets:ticket-update" ticket.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update
                </a>
            </div>
           
        
        
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ticket.cl_email}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Test Location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone</span>
          <span class="ml-auto text-gray-900">{{ ticket.cl_phone }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Subject</span>
          <span class="ml-auto text-gray-900">{{ ticket.ticket_subject }}</span>
        </div>
        <br />
        <br />   
        <p class="leading-relaxed mb-4">{{ ticket.cl_message }}</p>
        <div class="flex">

          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{% url "tickets:ticket-list" %}'>Back</a></button>
            
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
    
</body>
</html>

tickets/templates/ticket_update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update {{ ticket.cl_name }}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/dashboard_navbar.css' %}">
    <script src="{% static 'js/dashboard_navbar.js' %}"></script>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css'>
    
</head>
<body>

 <nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="{% url 'users:dashboard' %}">Navbar</a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-list' %}"><i class="far fa-clone"></i>Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-create' %}"><i class="fas fa-plus"></i>Create a ticket</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-chart-bar"></i>Charts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i>Sing Out</a>
                    </li>
                </ul>
            </div>
    </nav>
    
    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Ticket</h2>
                <input type="text" name='cl_name' class="text-gray-900 text-3xl title-font font-medium mb-4" value='{{ticket.cl_name}}' required></input>
                <div class="flex mb-4">
                <a href='{% url "tickets:ticket-detail" ticket.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a  class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Reviews
                </a>
                <a href='{% url "tickets:ticket-update" ticket.pk %}' class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update
                </a>
            </div>
                <form method='post'>
                    {% csrf_token %}
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Email</span>
                        <input  type="text" name='cl_email' class="ml-auto text-gray-900" value="{{ticket.cl_email}}" required></input>
                        </div>
                        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                        <span class="text-gray-500">Phone</span>
                        <input type="text" name='cl_phone' class="ml-auto text-gray-900" value="{{ticket.cl_phone }}" required></input>
                        </div>  
                        
                    <button type='success' class="btn btn-primary">Submit</button>
                
                </form>
                <br/>
                <a href='{% url "tickets:ticket-delete" ticket.pk %}'>
                    <button type='delete' class="btn btn-danger">
                        Delete
                    </button>
                </a>
                
                </div>
            
        </div>
    </div>
</section>    
    
</body>
</html>

users/templates/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Create </title>
</head>
<body>
    
    <h1>Register</h1>
<br /><br />
<div class="form-group">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Register</button>
    <a href="{% url 'users:dashboard' %}" class="btn btn-danger">Back</a>
</div>

</body>
</html>

users/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/dashboard_navbar.css' %}">
    <script src="{% static 'js/dashboard_navbar.js' %}"></script>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css'>

    
</head>
<body>
<!-- partial:index.partial.html -->
    <nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="{% url 'users:dashboard' %}">Navbar</a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-list' %}"><i class="far fa-clone"></i>Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tickets:ticket-create' %}"><i class="fas fa-plus"></i>Create a ticket</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:create-user' %}"><i class="fas fa-user-plus"></i>Add User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i>Sing Out</a>
                    </li>
                </ul>
            </div>
    </nav>
<!-- partial -->
  <script src='https://code.jquery.com/jquery-3.4.1.min.js'></script>
<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script><script  src="./script.js"></script>

</body>
</html>


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/dashboard_navbar.css' %}">
    <script src="{% static 'js/dashboard_navbar.js' %}"></script>
    <title>Dashboard</title>

</head>
<body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-address-book"></i>Address Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>Components</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:create-user' %}"><i class="fas fa-user-plus"></i>Add User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-copy"></i>Documents</a>
                </li>
            </ul>
        </div>
    </nav>
    
    
    
</html> {% endcomment %}